Update size-estimation.yml

diff --git a/.github/workflows/size-estimation.yml b/.github/workflows/size-estimation.yml
--- a/.github/workflows/size-estimation.yml
+++ b/.github/workflows/size-estimation.yml
@@ -11,27 +11,16 @@ jobs:
         env:
           HOME: /Users/himmel
         run: |
-          branches=(main jp/basic jp/movie jp/sound jp/unsupported)
-          cd /Users/himmel/gd-offline-res || exit 1
-          git config --global --add safe.directory /Users/himmel/gd-offline-res
-
-          git status
-          git branch
-          git branch -r
-
           for branch in "${branches[@]}"; do
-            echo "Checking out $branch..."
-            git checkout "$branch" >/dev/null 2>&1 || {
-              echo "Failed to checkout $branch"
-              continue
-            }
-  
-            echo "Calculating size for $branch..."
-  
-            size=$(git rev-list --objects "$branch" | \
-                   git cat-file --batch-check='%(objecttype) %(objectsize)' | \
-                   awk '$1=="blob"{sum+=$2}END{printf "%.2f MB", sum/1024/1024}')
-  
-            echo "$branch: $size"
-          done
+          echo "Checking out $branch..."
+          git checkout "refs/heads/$branch" >/dev/null 2>&1 || {
+            echo "Failed to checkout $branch"
+            continue
+          }
 
+          echo "Calculating size for $branch..."
+          size=$(git rev-list "refs/heads/$branch" --objects | \
+          git cat-file --batch-check='%(objecttype) %(objectsize)' | \
+          awk '$1=="blob"{sum+=$2}END{printf "%.2f MB", sum/1024/1024}')
+          echo "$branch: $size"
+          done
